# Generated by Django 3.0.3 on 2020-04-01 17:49

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=45)),
                ('address_line2', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=21)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Bathrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_shower', models.BooleanField(null=True)),
                ('has_bath', models.BooleanField(null=True)),
                ('has_sink', models.BooleanField(null=True)),
                ('has_fem_products', models.BooleanField(null=True)),
                ('has_toilet_paper', models.BooleanField(null=True)),
                ('num_of_toilets', models.IntegerField(default=0)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bathrooms', to='Air_PnP.Addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('personalEmail', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('home_address', models.CharField(blank=True, default='', max_length=150)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('title', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('bathroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Air_PnP.Bathrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Info',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payee', to='Air_PnP.Payment_Info')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payer', to='Air_PnP.Payment_Info')),
            ],
        ),
        migrations.AddField(
            model_name='addresses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
