# Generated by Django 3.0.3 on 2020-03-10 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=45)),
                ('address_line2', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Bathrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_shower', models.BooleanField(null=True)),
                ('has_bath', models.BooleanField(null=True)),
                ('has_sink', models.BooleanField(null=True)),
                ('has_fem_products', models.BooleanField(null=True)),
                ('has_toilet_paper', models.BooleanField(null=True)),
                ('num_of_toilets', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Air_PnP.Addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('personalEmail', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('title', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('bathroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Air_PnP.Bathrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Air_PnP.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Info',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Air_PnP.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payee', to='Air_PnP.Payment_Info')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payer', to='Air_PnP.Payment_Info')),
            ],
        ),
        migrations.AddField(
            model_name='addresses',
            name='user',
            field=models.ManyToManyField(to='Air_PnP.Users'),
        ),
    ]
