# Generated by Django 3.0.3 on 2020-03-25 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=21),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
