# Generated by Django 3.0.4 on 2020-04-22 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(blank=True, max_length=11)),
                ('bathroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayAvailable', to='Air_PnP.Bathrooms')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='home_city',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='users',
            name='home_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='users',
            name='home_zip',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.CharField(max_length=45),
        ),
        migrations.CreateModel(
            name='TimesAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('week_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesAvailable', to='Air_PnP.DayAvailable')),
            ],
        ),
    ]
