# Generated by Django 3.0.3 on 2020-03-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathrooms',
            name='avg_rating',
        ),
    ]
