# Generated by Django 3.0.4 on 2020-04-23 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0002_auto_20200422_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesavailable',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
