# Generated by Django 3.0.3 on 2020-03-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0002_remove_bathrooms_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
