# Generated by Django 3.0.3 on 2020-03-16 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0003_auto_20200310_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathrooms',
            name='address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='Air_PnP.Addresses'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='bathroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Air_PnP.Bathrooms'),
        ),
    ]
