# Generated by Django 3.0.4 on 2020-04-25 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0003_timesavailable_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timePeriod', models.TimeField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bathroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='Air_PnP.Bathrooms')),
            ],
        ),
    ]
