# Generated by Django 3.0.4 on 2020-04-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0005_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
