# Generated by Django 3.0.3 on 2020-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0005_auto_20200316_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_line2',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
