# Generated by Django 3.0.4 on 2020-04-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0007_auto_20200430_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathrooms',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='bathrooms/'),
        ),
        migrations.AlterField(
            model_name='bathrooms',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='bathrooms/'),
        ),
        migrations.AlterField(
            model_name='bathrooms',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='bathrooms/'),
        ),
        migrations.AlterField(
            model_name='bathrooms',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='bathrooms/'),
        ),
    ]
