# Generated by Django 3.0.4 on 2020-04-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0008_auto_20200430_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathrooms',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='bathroom_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bathrooms',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='bathroom_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bathrooms',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='bathroom_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bathrooms',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='bathroom_images/%Y/%m/%d/'),
        ),
    ]
