# Generated by Django 3.0.4 on 2020-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0009_auto_20200430_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_image',
            field=models.ImageField(blank=True, default='user_images/logo192.png', null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='bathrooms',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='bathroom_images/'),
        ),
        migrations.AlterField(
            model_name='bathrooms',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='bathroom_images/'),
        ),
        migrations.AlterField(
            model_name='bathrooms',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='bathroom_images/'),
        ),
        migrations.AlterField(
            model_name='bathrooms',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='bathroom_images/'),
        ),
    ]
