# Generated by Django 3.0.4 on 2020-05-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0010_auto_20200509_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.ImageField(blank=True, default='user_images/default_user_image.png', null=True, upload_to='user_images/'),
        ),
    ]
