# Generated by Django 3.0.4 on 2020-05-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0012_auto_20200510_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesavailable',
            name='week_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesAvailable', to='Air_PnP.DayAvailable'),
        ),
    ]
