# Generated by Django 3.0.4 on 2020-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0014_auto_20200510_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathrooms',
            name='post_called',
            field=models.BooleanField(default=False),
        ),
    ]
