# Generated by Django 3.0.4 on 2020-05-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Air_PnP', '0015_bathrooms_post_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathrooms',
            name='post_called',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
